version: 1
default_environment: dev
project_id: da2d0b24-f518-4575-96f8-3e8478255f9a
environments:
- name: dev
- name: staging
- name: prod
send_anonymous_usage_stats: false
plugins:
  extractors:
  - name: tap-beautifulsoup
    variant: meltanolabs
    pip_url: git+https://github.com/MeltanoLabs/tap-beautifulsoup.git@v0.1.0
    config:
      source_name: sdk-docs
      site_url: https://datacisions.com #OLD VALUE: https://sdk.meltano.com/en/latest/
      output_folder: output
      parser: html.parser
      download_recursively: true
      find_all_kwargs:
        attrs:
          role: main
  - name: tap-csv
    pip_url: git+https://github.com/sbalnojan/tap-csv.git
    config:
      files:
      - entity: doc
        path: ./data/mental_models.csv
        keys: [id]
        delimiter: ;
      add_metadata_dict: True

  loaders:
  - name: target-pinecone
    variant: meltanolabs
    pip_url: git+https://github.com/MeltanoLabs/target-pinecone.git@v0.2.0
    config:
      document_text_property: page_content
      embeddings_property: embeddings
    #  metadata_property: metadata
      pinecone_metadata_text_key: text
      load_method: overwrite
  - name: target-jsonl
    variant: andyh1203
    pip_url: target-jsonl
  utilities:
  - name: streamlit_app
    namespace: streamlit_app
    pip_url: langchain streamlit openai pinecone-client tiktoken
    commands:
      demo_ui:
        args: run demo_ui/llm_app_ui.py
        executable: streamlit
  mappers:
  - name: meltano-map-transformer
    pip_url: git+https://github.com/MeltanoLabs/meltano-map-transform.git
    executable: meltano-map-transform
    mappings:
    - name: add-meta
      config:
        stream_maps:
          doc:
            id: id 
            page_content: page_content 
            metadata: #dict({1:"2"})
              source: '\"client-123\"' #data/mental_models.csv #str("data/mental_models.csv")
              time_extracted: '\"client-123\"' #"2023-08-23T13:16:34.631170+00:00"

  - name: map-gpt-embeddings
    variant: meltanolabs
    pip_url: git+https://github.com/meltanolabs/map-gpt-embeddings.git@50e35fa3912a88a47d0971870176f604c68fd73e
    mappings:
    - name: add-embeddings
      config:
        document_text_property: page_content
   #     document_metadata_property: metadata
  - name: mapper-generic
    namespace: mapper_generic
    pip_url: git+https://github.com/pnadolny13/mapper-generic.git@cdb09aec80d9c139784190959c0a9a801cdaf269
    executable: mapper-generic
    mappings:
    - name: clean-text
      config:
        code_path: mappers/clean_text.py
jobs:
- name: reload_pinecone
  tasks:
  - tap-beautifulsoup clean-text add-embeddings target-pinecone
- name: test_csv
  tasks:
  - tap-csv clean-text target-jsonl #add-meta target-jsonl
- name: test_csv_2
  tasks:
  - tap-csv clean-text add-meta add-embeddings target-jsonl
schedules:
- name: reload_pinecone
  interval: 0 0 * * 0
  job: reload_pinecone
